GET http://api.openweathermap.org/data/2.5/weather?q=Caracas&lang=es&units=metric&appid=cfdf46ac4ccb5e3a4775488af2e57ce0

###

GET http://openweathermap.org/img/wn/02d@2x.png

###

GET https://api.openweathermap.org/data/2.5/onecall?lat=10.488&lon=-66.8792&lang=es&exclude=minutely,hourly&units=metric&appid=cfdf46ac4ccb5e3a4775488af2e57ce0    
